### ISSUE TITLE
SAL.FS: copyDirTree method with ignoring files, don't work with sub directories.

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtecharchive/jumpscaleX_core#59]
### Steps:
1- Create a directory `test_dir`.
2- Create a file `test_file` inside `test_dir`.
3- Create a sub directory `subdir` under `test_dir`.
4- Create a file `file` insdie `subdir`.
5- Copy this `test_dir` to `test_dir2` with ignoring files `["test_file", "file"]`
```
j.sal.fs.copyDirTree("/tmp/test_dir", "/tmp/test_dir2", ignorefiles=["test_file", "file"]) 
```
### Expected Result:
find `test_dir` and `subdir` only without any files.
### Actual Result:
Both files are copied.
```
3BOTDEVEL:3bot:tmp: ls test_dir2
subdir  test_file
3BOTDEVEL:3bot:tmp: ls test_dir2/subdir/
file
```

### The Problem:
As `rsync=True`,  it ignores `ignorefiles` and copy all files.

#### So if `rsync=False` should solve this.
1- Delete test_dir2.
2- Copy it again with `rsync=False`.
```
j.sal.fs.copyDirTree("/tmp/test_dir", "/tmp/test_dir2", ignorefiles=["test_file", "file"], rsync=False)
```
### Actual Result:
The file under `test_dir` is  copied, but the file under `subdir` is not copied.
```
3BOTDEVEL:3bot:tmp: ls test_dir2
subdir
3BOTDEVEL:3bot:tmp: ls test_dir2/subdir/
file
```
### The problem:
copyDirTree is called recursively for sub directories and `rsync` is not passed so `ignorefiles` is ignored.

**Comment by waleedhammam** [comment]
fixed at: https://github.com/threefoldtech/jumpscaleX_core/commit/d2c424e77926ac0809c45d21111ce6b51d138eae

**Comment by hossnys** [comment]
verified on development d2c424e

```
3BOTDEVEL:3bot:tmp: cd test_dir2
3BOTDEVEL:3bot:test_dir2: ls
subdir
3BOTDEVEL:3bot:test_dir2: cd subdir/
3BOTDEVEL:3bot:subdir: ls
3BOTDEVEL:3bot:subdir: 
```
